### ISSUE TITLE
Possibly wrong output on "private" dependency

### ISSUE THREAD

**Issue by leucos** [psampaz/go-mod-outdated#12]
It seems that in my case `go-mod-outdated` recommends an older version:
```
$ go list -u -m -json all 2>/dev/null | go-mod-outdated -update -direct
+-------------------------+--------------------------------------+-------------+--------+------------------+
|          MODULE         |               VERSION                | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+-------------------------+--------------------------------------+-------------+--------+------------------+
| some.private.dependency | v0.1.1-0.20190429140155-8759a946d40b | v0.1.0      | true   | false            |
+-------------------------+--------------------------------------+-------------+--------+------------------+
```

The repository for the dependency is private.

Am I missing something here ?

Thanks !

- go version go1.12 linux/amd64
- go-mod-outdated: v0.3.0

**Comment by psampaz** [comment]
Hi, thanks for submitting this issue.

I am pretty sure that the case is this one https://github.com/psampaz/go-mod-outdated#invalid-timestamps.

If you want to see more details for this issue please go though this ["New version" isn't always newer ](https://github.com/psampaz/go-mod-outdated/issues/1)

but please submit the output of **go list -u -m -json all** to check if there is something different

**Comment by leucos** [comment]
Indeed, it is exactly that. Sorry for the noise !
