### ISSUE TITLE
Windows Defender indicates go-mod-outdated@v0.9.0 is trojan

### ISSUE THREAD

**Issue by wtask** [psampaz/go-mod-outdated#61]
Windows 11, go-mod-outdated.exe v0.9.0 installed via `go install github.com/psampaz/go-mod-outdated@latest`
Windows Defender stop running go-mod-outdated binary with critical level:

Trojan:Win32/Wacatac.B!ml
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505

Version v0.8.0 works as expected.

**Comment by psampaz** [comment]
Hi Mike, thanks for reporting this.

I do not have access to a window machine so I cannot check myself. 

go-mod-outdated.exe is built locally on your machine when you run the `go install github.com/psampaz/go-mod-outdated@latest` and it is not something that you download from go-mod-outdated [release](https://github.com/psampaz/go-mod-outdated/releases/tag/v0.9.0)

In case you haven't done this already, can you please delete v0.9.0 go-mod-outdated.exe, run 

`go install github.com/psampaz/go-mod-outdated@v0.8.0`

and the run go-mod-outdated.exe again?

**Comment by wtask** [comment]
@psampaz Yes, I ran local installation with go 1.20.1 as @latest and as @v0.9.0 - all the same. Reinstalling @v0.8.0 solves the problem, except it is not latest version. I didn't download any release artifacts.

**Comment by psampaz** [comment]
Please check the following

https://go.dev/doc/faq#virus
https://github.com/golang/go/issues/55042
https://github.com/golang/go/issues/47807#issuecomment-901700449

**Comment by wtask** [comment]
Thanks for the links. Let's see.

**Comment by wtask** [comment]
Windows Defender false positives have stopped
